"""remove country column from click

Revision ID: 67076b87a3ad
Revises: c73ab84f790e
Create Date: 2026-07-26 01:24:45.425188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67076b87a3ad'
down_revision: Union[str, Sequence[str], None] = 'c73ab84f790e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE clicks DROP COLUMN IF EXISTS country")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('country', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
