"""create users, urls, clicks tables

Revision ID: c73ab84f790e
Revises: 
Create Date: 2026-07-22 00:28:56.267521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c73ab84f790e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS short_urls")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('short_urls_pkey')),
    sa.UniqueConstraint('original_url', name=op.f('short_urls_original_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('short_code', name=op.f('short_urls_short_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
